docs/advanced/advanced.md
docs/connector/clickhouse.md
docs/connector/es.md
docs/connector/http.md
docs/connector/jdbc.md
docs/connector/kafka.md
docs/connector/mongo.md
docs/connector/redis.md
docs/console/deploy.md
docs/console/deployment.md
docs/console/quickstart.md
docs/flink-k8s/1-deployment.md
docs/flink-k8s/2-k8s-pvc-integration.md
docs/flink-k8s/3-hadoop-resource-integration.md
docs/flinksql/flinksql.md
docs/model/conf.md

提交内容：
迁移streamx md文档至新官网项目
解决方案：
1、md文档修改为 docusaurus 要求的解析格式
2、kafka.md Kafka Sink 信息表格图标改为文字，如图：

feat(streamx doc file): add streamx doc file

---

docs/components/TableData.jsx
docs/components/Toast.js
docs/development/conf.md
docs/development/model.md

2022 New StreamX website

---

.github/workflows/deploy.yaml

actions update

---

.github/workflows/deploy.yaml

actions support.

---

docs/user-guide/quickstart.md
src/pages/home/index.jsx

video url change.

---

docs/connector/jdbc.md

将 'if (lastOne ** null) "2020-12-16 12:00:00" else lastOne.timestamp'
修改为 'if (lastOne == null) "2020-12-16 12:00:00" else lastOne.timestamp'

[FixBug] 修改 if 条件判断内容表达错误

---

docs/components/Toast.js
docs/connector/clickhouse.md
docs/connector/http.md
docs/connector/jdbc.md

this  pr content：
add streamx clickhouseSink\httpSink  doc file

feat(streamx doc file): add streamx clickhouseSink\httpSink  doc file

---

docs/connector/hbase.md
docs/connector/jdbc.md
docs/connector/kafka.md
docs/connector/redis.md

add Streamx RedisSink doc file

add Streamx RedisSink doc file

---

docs/connector/clickhouse.md
docs/connector/http.md
docs/connector/jdbc.md
docs/connector/redis.md

Optimizing document structure

---

docs/user-guide/deployment.md

user need workspace dir permission. /opt often belong to root. add note.

[minor] add workspace dir note

---

docs/connector/doris.md

doc for the https://github.com/streamxhub/streamx/pull/736

[doc][connector] add doris Connector doc

---

docs/user-guide/development.md

fix  development.md file desc error

fix(doc): fix  development.md file desc error

---

docs/user-guide/development.md

app.home路径中间存在空格会报错

---

docs/flink-k8s/1-deployment.md

[document optimization]streamx for Flink on k8s

[document optimization]streamx for Flink on k8s

---

docs/flinksql/4-data-type.md

add flink sql data type document.

add flink sql document

---

package.json

node update version

---

package.json

docusaurus update to 2.0.1

---

docs/flinksql/3-read-write-hive.md
docs/flinksql/4-data-type.md
docs/flinksql/udf/2-udf.md

modify some doc error.

---

docs/user-guide/dockerDeployment.md

modify typo and add switch directory command docs/user-guide/dockerDeployment.md

modify typo and add switch directory command docs/user-guide/dockerDeployment.md

---

docs/connector/7-http.md
docs/development/alert-conf.md

HTTP-Connector and Alert configurations document in English has been added. I would appreciate it if you like to optimize this document.

Add HTTP-Connector and Alert configurations English version document

---

docs/flink-k8s/2-k8s-pvc-integration.md

add translation to k8s-pvc-integration md

translate k8s-pvc-integration

---

docs/advanced/advanced.md
docs/connector/2-jdbc.md
docs/connector/3-clickhouse.md
docs/connector/4-doris.md
docs/connector/5-es.md
docs/connector/6-hbase.md
docs/flink-k8s/2-k8s-pvc-integration.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/connector/2-jdbc.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/flink-k8s/2-k8s-pvc-integration.md
src/pages/home/languages.json
src/pages/user/languages.json

docs: mirror fix

---

docs/user-guide/development.md

docs: need assign scala version

---

docs/user-guide/rainbondDeployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/rainbondDeployment.md

Signed-off-by: Qi Zhang <smallqi1@163.com>

docs: add rainbond deployment docs

---

src/pages/home/hero.jsx

style: change home style

---

.gitignore

Add the IDEA git ignore

---

community/contribution_guide/become_committer.md
community/contribution_guide/become_pmc_member.md

Fix the contribution guide

---

docs/components/TableData.jsx
docs/components/data.js
docs/development/conf.md

Update the StreamPark configuration doc
close https://github.com/apache/incubator-streampark/issues/1751

Update the StreamPark configuration doc

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/3-development.md

Fix "modify configuration" link failure bug

Fix "modify configuration" link failure bug

---

src/pages/home/theme.less

[improve] sync home page color

---

docs/user-guide/4-dockerDeployment.md

After wget, I got some html files, so I want to fix these links.

Fix wget links

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/3-development.md

1. improve sentence fluency
2. fix some typo

[Improve][Docs][User-Guide] Improve the develop environment document

---

docs/user-guide/1-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/1-deployment.md

Add deployment detail about mysql's user.

[doc] [add] Add deployment detail about mysql's user.

---

docusaurus.config.js
src/pages/download/data.json
src/pages/download/release-note/2.0.0.md

[Feature] release-note 2.0.0 document add

[Feature] release-note 2.0.0 document add

---

community/release/how-to-verify.md

[Feature] how to verify release

[Feature] how to verify release

---

community/release/how-to-verify.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current.json
i18n/zh-CN/docusaurus-plugin-content-docs-community/release/how-to-verify.md

add how-to-verify docs

---

README_ZH.md
blog/Flink开发利器StreamPark.md
src/pages/download/languages.json
src/pages/home/languages.json

modify format and fix typos

---

src/pages/download/data.json
src/pages/download/index.jsx
src/pages/download/table.jsx

2.0.0 release

---

src/pages/user/images.json
src/pages/user/index.js

Add a redirect using user link

improve: Add a redirect using user link

---

community/release/_category_.json
community/submit_guide/items-need-to-note.md

[Issue-2469][Improve][exception process rule] Add the document page about exception processing rule.
https://github.com/apache/incubator-streampark/issues/2469

[Issue-2469][Improve][exception process rule] Add the document page about exception processing rule.

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/8-YarnQueueManagement.md

添加yarn队列管理的汉化

---

src/pages/download/table.jsx

update download link

---

docs/user-guide/2-quickstart.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/2-quickstart.md

improve 2-qucikstart.md_CN .The link is still https://github.com/streamxhub/streamx-quickstart.git old link

improve docs

---

docs/flink-k8s/1-deployment.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/flink-k8s/1-deployment.md

Issue Number: close [#2983](https://github.com/apache/incubator-streampark/issues/2983)

[ISSUE-2983] Fix the wrong doc description.

---

.gitignore
i18n/zh-CN/docusaurus-theme-classic/navbar.json

fix(nav): translation community navbar

---

src/css/custom.css

**improve  doc sidebar style**

improve(sidebar): improve sidebar style

---

docusaurus.config.js
src/css/custom.css
src/pages/download/index.less
src/pages/home/feature.jsx
src/pages/home/hero.jsx
src/pages/home/index.less
src/pages/home/performance.jsx
src/pages/home/performance.less
src/pages/team/index.less
src/pages/user/index.less
src/styles/base.less

1. nav bar style
2. dark theme switch
home
document

style: nav bar & dark color theme

---

src/pages/download/index.less
src/pages/team/index.jsx
src/pages/team/index.less

style: team page style and download style

---

blog/0-streampark-flink-on-k8s.md
i18n/zh-CN/docusaurus-plugin-content-blog/0-streampark-flink-on-k8s.md
i18n/zh-CN/docusaurus-plugin-content-blog/1-flink-framework-streampark.md
i18n/zh-CN/docusaurus-plugin-content-blog/2-streampark-usercase-chinaunion.md
i18n/zh-CN/docusaurus-plugin-content-blog/3-streampark-usercase-bondex-paimon.md
i18n/zh-CN/docusaurus-plugin-content-blog/4-streampark-usercase-shunwang.md
i18n/zh-CN/docusaurus-plugin-content-blog/5-streampark-usercase-dustess.md
i18n/zh-CN/docusaurus-plugin-content-blog/6-streampark-usercase-joyme.md
i18n/zh-CN/docusaurus-plugin-content-blog/7-streampark-usercase-haibo.md

Translate blog posts
Note that when writing blog posts, the blog directory is an English blog, i18n/zh-CN/docusaurus-plugin-content-blog
See details: https://docusaurus.io/zh-CN/docs/i18n/introduction

fix: translate blog article

---

blog/2-streampark-usercase-chinaunion.md

[Improve] Localization streampark-usercase-chinaunion

[Improve] Localization streampark-usercase-chinaunion

---

docs/user-guide/10-SSO.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/10-SSO.md

Add few notes for SSO login, which comes from the some questions user ask.

Add notes for SSO login

---

src/css/custom.css

fix: doc sidebar font style

---

blog/6-streampark-usercase-joyme.md

see: https://github.com/apache/incubator-streampark/issues/3218
cc: @caicancai @saLeox

[Improve] Localization streampark-usercase-joyme

---

blog/5-streampark-usercase-dustess.md

see: https://github.com/apache/incubator-streampark/issues/3218
cc: @caicancai @saLeox

[Improve] Localization streampark-usercase-dustess

---

blog/4-streampark-usercase-shunwang.md

see: https://github.com/apache/incubator-streampark/issues/3218
cc: @caicancai @saLeox

[Improve] Localization streampark-usercase-shunwang

---

src/pages/home/hero.jsx
src/pages/home/index.less

fix: hero style

---

blog/0-streampark-flink-on-k8s.md
blog/1-flink-framework-streampark.md
i18n/zh-CN/docusaurus-plugin-content-blog/0-streampark-flink-on-k8s.md

Review and improve the translation for two blog articles.

Review and Improve the translation for blog articles

---

src/pages/download/release-note/2.1.2.md

Append release note for 2.1.2

---

i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/11-platformInstall.md
i18n/zh-CN/docusaurus-plugin-content-docs/current/user-guide/12-platformBasicUsage.md

1. Improve documentation related to platform installation and basic usage
2. Areas that need to be improved have been highlighted in red in the document

[Improve] Improve documentation related to platform installation and basic usage

---

docs/user-guide/12-platformBasicUsage.md

[improve] localization platform basic usage

---

docs/user-guide/11-platformInstall.md
yarn.lock

[Improve] localization platform install

---

docs/components/data.js
i18n/zh-CN/docusaurus-plugin-content-docs/current/components/data.js

[Improve]modify user-guide/development nodejs version description

---

blog/8-streampark-usercase-ziru.md

[Improve] localization Ziroom's Real-Time Computing Platform Practice Based on Apache StreamPark

---

blog/8-streampark-usercase-ziru.md
i18n/zh-CN/docusaurus-plugin-content-blog/8-streampark-usercase-ziru.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/contribution_guide/become_committer.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/contribution_guide/become_pmc_member.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/release/How-to-release.md

[fix] fix duplicate apache
@caicancai

[Fix] fix duplicate apache

---

src/pages/download/languages.json

English corrections

---

src/pages/team/index.jsx
src/pages/user/index.jsx

See https://lists.apache.org/thread/3fosfz2jv0yhcrzt6mtwbwtxg4vtwxpy for more details.

Render more HTML for JSX pages

---

docs/intro.md

line 11: corrected grammar and some noun-verb alignments
line 15: if you have 'including' at the start of a list, you do not need 'etc.' at the end.
line 17: a question requires a ? at the end
line 21: removed repetition
lines 30 and 63: removed empty bullet point
line 33: changed 'three parts' to 'two parts'
lines 41 and 64: rewrote sentences

Update intro.md text changes to improve readability

---

docs/user-guide/1-deployment.md

simplified text and improved layout throughout
line 17: removed repetitions
line 93 did not make sense. I have tried to improve it, but may have the intention wrong.

Update 1-deployment.md minor text edits

---

src/pages/download/table.jsx

Go direct to download

---

src/pages/download/index.jsx
src/pages/download/languages.json

[Improve] Downloads: not clear how to choose between 2.12 and 2.11

[Improve] Describe how to choose between 2.12 and 2.11 in Downloads

---

community/release/How-to-release.md
i18n/zh-CN/docusaurus-plugin-content-docs-community/current/release/How-to-release.md

update release step and fix link

[Improve] Update How-to-release.md

---

src/css/bootstrap.min.css
src/pages/home/feature.jsx
src/pages/home/hero.jsx
src/pages/home/index.less
src/pages/home/languages.json
src/pages/home/performance.jsx

change log:
- All Flink keywords changed to Flink®
- All Spark keywords changed to Spark™
- Font color has been improved in the dark theme

[Improve] core features description improvement

---

docs/get-started/3.dockerDeployment.md

fix link address

---

docusaurus.config.js
src/css/custom/default.less
src/css/custom/index.less

- Adjust the light color of the code block for the light theme

[Improve] code block style on light theme

---

community/contribution_guide/SP-License.md
community/contribution_guide/SPIP.md
community/contribution_guide/commit-message.md
community/contribution_guide/contribute.md
community/contribution_guide/document.md
community/contribution_guide/e2e-guide.md
community/contribution_guide/pull-request.md

Improve contribution guide
I've test successfully locally.

[Doc] Improve contribution guide

---

src/pages/team/languages.json

[Chore] Update team
